### ISSUE TITLE
Warn if the package module is missing a docstring

### ISSUE THREAD

**Issue by IanButterworth** [JuliaRegistries/RegistryHealthChecks.jl#2]
If a module is missing a docstring and a user tries `help?> Package`, currently nothing shows. https://github.com/JuliaLang/julia/pull/39093 aims to print the README contents

But, it would be good to promote the addition of carefully crafted docstrings for the main module in the package, as they would likely be better crafted for purpose.

Could the merge bot warn if there isn't one?
Perhaps there are other best-practices to check for too?

**Comment by DilumAluthge** [comment]
Closing in favor of https://github.com/giordano/AnalyzeRegistry.jl/issues/35
